Repository iiasa/ixmp4, pull requests merged in 2024-03, with the labels that each got.

#54 add iamc filter for tabulate/ list runs
  ixmp4/data/db/run/filter.py
  tests/core/test_run.py
Labels: enhancement

#59 Fetch tags in CI for correct version
  .github/workflows/build-docs.yaml
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
Labels: enhancement

#60 Fix typo in action input
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
Labels: bug

#61 Add needed [dataframe] extra for dask
  ixmp4/core/iamc/data.py
  poetry.lock
  pyproject.toml
Labels: bug

#65 Fix RTD builds with poetry
  .github/workflows/build-docs.yaml
  .readthedocs.yaml
Labels: documentation

#75 Clarify CI test names
  .github/workflows/pytest.yaml
Labels: enhancement
